In [2]:
##Q.1)= Generate a list of 100 integers containing values between 90 to 130 and store it in the variable `int_list`. 
#After generating the list, find the following :

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statistics

In [36]:
int_list = np.random.randint(90,130,100)
int_list

array([127, 121,  98, 103, 123, 118, 104, 101,  91, 104, 101, 119,  97,
       129, 104,  92,  90, 127, 104,  90, 117, 117, 112, 116, 107, 110,
       109, 122, 104, 124, 104, 111,  98, 111,  99,  90, 128,  96, 103,
        99,  99,  95,  91, 126,  94, 124,  91, 105, 119, 120, 118, 103,
       127, 129,  92,  95,  93, 110, 122, 129, 110,  97, 107,  90, 119,
        96, 105, 106, 102, 114,  97, 121, 104, 118, 127, 120, 102, 117,
       108, 122, 109,  97, 112,  98, 125,  90, 104, 120, 120, 101, 123,
       109,  92, 123, 109,  90, 128, 104, 122, 111])

In [4]:
#(i) Write a Python function to calculate the mean of a given list of numbers.Create a function to find the median of a list of numbers.

##finding mean of int_list
np.mean(int_list)



109.67

In [5]:
##finding median of int_list
np.median(int_list)

109.0

In [8]:
##(ii) Develop a program to compute the mode of a list of integers.

statistics.mode(int_list)

126

In [41]:
## (iii) Implement a function to calculate the weighted mean of a list of values and their corresponding weights.

def weighted_mean(values, weights):
    if not values or not weights or len(values) != len(weights):
        return None  # Return None if either values or weights are empty or if their lengths don't match

    weighted_sum = sum(value * weight for value, weight in zip(values, weights))
    total_weight = sum(weights)
    return weighted_sum / total_weight

# Example usage:
values = [2, 4, 8, 16, 32]
weights = [1, 2, 3, 4, 5]
result = weighted_mean(values, weights)
if result is not None:
    print("Weighted mean:", result)
else:
    print("Either values or weights are empty, or their lengths don't match.")



Weighted mean: 17.2


In [34]:
##  (iv) Write a Python function to find the geometric mean of a list of positive numbers.

from math import prod, pow

def positive_geometric_mean(numbers):
    positive_numbers = [x for x  in numbers if x > 0]
    if not positive_numbers:
        return None  # No positive numbers in the list
    product = prod(positive_numbers)
    return pow(product, 1/len(positive_numbers))

# Example usage:

result = positive_geometric_mean(int_list)
if result is not None:
    print("Geometric mean of positive numbers:", result)
else:
    print("No positive numbers in the list.")




Geometric mean of positive numbers: 8.000000000000002


In [31]:
##(v) Create a program to calculate the harmonic mean of a list of values.

def harmonic_mean(numbers):
    if not numbers:
        return None  # Return None if the list is empty

    reciprocal_sum = sum(1/x for x in numbers)
    return len(numbers) / reciprocal_sum

# Example usage:

result = harmonic_mean(int_list)
if result is not None:
    print("Harmonic mean:", result)
else:
    print("The list is empty.")


Harmonic mean: 5.161290322580645


In [39]:
## (vi) Build a function to determine the midrange of a list of numbers (average of the minimum and maximum).

def midrange(numbers):
    if not numbers:
        return None  # Return None if the list is empty

    min_val = min(numbers)
    max_val = max(numbers)
    return (min_val + max_val) / 2

# Example usage:
int_list = [34,5,3,21,65,24]
result = midrange(int_list)
if result is not None:
    print("Midrange:", result)
else:
    print("The list is empty.")


Midrange: 34.0


In [40]:
## (vii) Implement a Python program to find the trimmed mean of a list, excluding a certain percentage of outliers.  

def trimmed_mean(numbers, percentage):
    if not numbers:
        return None  # Return None if the list is empty

    sorted_numbers = sorted(numbers)
    trim_count = int(len(sorted_numbers) * percentage / 100)
    trimmed_numbers = sorted_numbers[trim_count:-trim_count]
    return sum(trimmed_numbers) / len(trimmed_numbers)

# Example usage:
my_list = [2, 4, 8, 16, 32]
percentage = 20  # Exclude 20% of outliers (10% from each end)
result = trimmed_mean(my_list, percentage)
if result is not None:
    print("Trimmed mean ({}%):".format(percentage), result)
else:
    print("The list is empty.")




Trimmed mean (20%): 9.333333333333334


In [1]:
# 3) Write a Python class representing a discrete random variable with methods to calculate its expected value and variance.
class DiscreteRandomVariable:
    def __init__(self, values, probabilities):
        """
        Initializes the DiscreteRandomVariable instance.

        :param values: List of possible values of the random variable.
        :param probabilities: List of probabilities corresponding to the values.
        """
        if len(values) != len(probabilities):
            raise ValueError("The length of values and probabilities must be the same.")
        if any(p < 0 or p > 1 for p in probabilities):
            raise ValueError("Probabilities must be between 0 and 1.")
        if abs(sum(probabilities) - 1) > 1e-10:
            raise ValueError("The sum of probabilities must be 1.")

        self.values = values
        self.probabilities = probabilities

    def expected_value(self):
        """
        Calculates the expected value of the discrete random variable.

        :return: The expected value.
        """
        return sum(v * p for v, p in zip(self.values, self.probabilities))

    def variance(self):
        """
        Calculates the variance of the discrete random variable.

        :return: The variance.
        """
        mu = self.expected_value()
        return sum(p * (v - mu) ** 2 for v, p in zip(self.values, self.probabilities))

# Example usage
values = [1, 2, 3, 4]
probabilities = [0.1, 0.2, 0.3, 0.4]

rv = DiscreteRandomVariable(values, probabilities)
print("Expected Value:", rv.expected_value())
print("Variance:", rv.variance())


Expected Value: 3.0
Variance: 1.0


In [3]:
#4) Implement a program to simulate the rolling o6 a 6air six-sided die and calculate the expected value and variance o6 the outcomes.
import random

class FairDie:
    def __init__(self, sides=6):
        self.sides = sides
        self.values = list(range(1, sides + 1))
        self.probabilities = [1 / sides] * sides

    def roll(self):
        return random.choice(self.values)

    def expected_value(self):
        return sum(v * p for v, p in zip(self.values, self.probabilities))

    def variance(self):
        mu = self.expected_value()
        return sum(p * (v - mu) ** 2 for v, p in zip(self.values, self.probabilities))

def simulate_die_rolls(num_rolls=10000):
    die = FairDie()
    rolls = [die.roll() for _ in range(num_rolls)]

    # Calculate empirical expected value and variance
    empirical_mean = sum(rolls) / num_rolls
    empirical_variance = sum((x - empirical_mean) ** 2 for x in rolls) / num_rolls

    return empirical_mean, empirical_variance



In [4]:
#5) Create a Python function to generate random samples 6rom a given probability distribution (e.g., binomial, Poisson) and calculate their mean and variance.
import numpy as np

def generate_samples(distribution, params, num_samples):
    """
    Generates random samples from a given probability distribution and calculates their mean and variance.

    :param distribution: A string specifying the distribution ('binomial', 'poisson').
    :param params: A tuple containing the parameters for the distribution.
                   - For 'binomial': (n, p)
                   - For 'poisson': (lambda,)
    :param num_samples: The number of samples to generate.
    :return: A tuple containing the mean and variance of the generated samples.
    """
    if distribution == 'binomial':
        n, p = params
        samples = np.random.binomial(n, p, num_samples)
    elif distribution == 'poisson':
        lam = params[0]
        samples = np.random.poisson(lam, num_samples)
    else:
        raise ValueError("Unsupported distribution. Use 'binomial' or 'poisson'.")

    mean = np.mean(samples)
    variance = np.var(samples)
    
    return mean, variance

# Example usage
num_samples = 10000

# Binomial distribution parameters: n = 10, p = 0.5
binomial_mean, binomial_variance = generate_samples('binomial', (10, 0.5), num_samples)
print(f"Binomial Distribution - Mean: {binomial_mean:.2f}, Variance: {binomial_variance:.2f}")

# Poisson distribution parameter: lambda = 5
poisson_mean, poisson_variance = generate_samples('poisson', (5,), num_samples)
print(f"Poisson Distribution - Mean: {poisson_mean:.2f}, Variance: {poisson_variance:.2f}")


Binomial Distribution - Mean: 4.99, Variance: 2.49
Poisson Distribution - Mean: 5.00, Variance: 5.13


In [5]:
#6) Write a Python script to generate random numbers 6rom a Gaussian (normal) distribution and compute the mean, variance, and standard deviation o6 the samples.
import numpy as np

def generate_gaussian_samples(mean, std_dev, num_samples):
    """
    Generates random samples from a Gaussian (normal) distribution and calculates their mean, variance, and standard deviation.

    :param mean: The mean of the Gaussian distribution.
    :param std_dev: The standard deviation of the Gaussian distribution.
    :param num_samples: The number of samples to generate.
    :return: A dictionary containing the mean, variance, and standard deviation of the generated samples.
    """
    # Generate random samples from a Gaussian distribution
    samples = np.random.normal(loc=mean, scale=std_dev, size=num_samples)
    
    # Calculate mean, variance, and standard deviation
    sample_mean = np.mean(samples)
    sample_variance = np.var(samples)
    sample_std_dev = np.std(samples)

    return {
        'mean': sample_mean,
        'variance': sample_variance,
        'std_dev': sample_std_dev
    }

# Example usage
mean = 0
std_dev = 1
num_samples = 10000

results = generate_gaussian_samples(mean, std_dev, num_samples)

print(f"Generated Samples - Mean: {results['mean']:.2f}")
print(f"Generated Samples - Variance: {results['variance']:.2f}")
print(f"Generated Samples - Standard Deviation: {results['std_dev']:.2f}")


Generated Samples - Mean: -0.00
Generated Samples - Variance: 1.00
Generated Samples - Standard Deviation: 1.00


In [6]:
# 7) Write a Python 6unction to calculate the probability density 6unction (PDF) o6 a continuous random variable 6or a given normal distribution.
import numpy as np

def normal_pdf(x, mean, std_dev):
    """
    Calculates the probability density function (PDF) of a normal distribution.

    :param x: The value at which to evaluate the PDF.
    :param mean: The mean of the normal distribution.
    :param std_dev: The standard deviation of the normal distribution.
    :return: The PDF value at the given x.
    """
    coefficient = 1 / (std_dev * np.sqrt(2 * np.pi))
    exponent = np.exp(- (x - mean) ** 2 / (2 * std_dev ** 2))
    pdf_value = coefficient * exponent
    return pdf_value

# Example usage
mean = 0
std_dev = 1
x_values = [ -2, -1, 0, 1, 2 ]

pdf_values = {x: normal_pdf(x, mean, std_dev) for x in x_values}

for x, pdf in pdf_values.items():
    print(f"PDF at x={x}: {pdf:.4f}")


PDF at x=-2: 0.0540
PDF at x=-1: 0.2420
PDF at x=0: 0.3989
PDF at x=1: 0.2420
PDF at x=2: 0.0540


In [7]:
# 9) Create a program to calculate the cumulative distribution 6unction (CDF) o6 exponential distribution
import numpy as np

def exponential_cdf(x, lambda_):
    """
    Calculates the cumulative distribution function (CDF) of an exponential distribution.

    :param x: The value at which to evaluate the CDF.
    :param lambda_: The rate parameter of the exponential distribution (1/mean).
    :return: The CDF value at the given x.
    """
    if x < 0:
        return 0.0
    return 1 - np.exp(-x / lambda_)

# Example usage
lambda_ = 1.0  # Rate parameter (1/mean)
x_values = [0, 1, 2, 3, 4, 5]

cdf_values = {x: exponential_cdf(x, lambda_) for x in x_values}

for x, cdf in cdf_values.items():
    print(f"CDF at x={x}: {cdf:.4f}")


CDF at x=0: 0.0000
CDF at x=1: 0.6321
CDF at x=2: 0.8647
CDF at x=3: 0.9502
CDF at x=4: 0.9817
CDF at x=5: 0.9933


In [8]:
# 10) Write a Python 6unction to calculate the probability mass 6unction (PMF) o6 Poisson distribution
import numpy as np
from scipy.special import factorial

def poisson_pmf(k, lambda_):
    """
    Calculates the probability mass function (PMF) of a Poisson distribution.

    :param k: The number of occurrences (non-negative integer).
    :param lambda_: The rate parameter (mean) of the Poisson distribution.
    :return: The PMF value for the given k.
    """
    if k < 0 or not isinstance(k, int):
        raise ValueError("k must be a non-negative integer.")
    return (lambda_ ** k * np.exp(-lambda_)) / factorial(k)

# Example usage
lambda_ = 5.0  # Rate parameter (mean)
k_values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

pmf_values = {k: poisson_pmf(k, lambda_) for k in k_values}

for k, pmf in pmf_values.items():
    print(f"PMF at k={k}: {pmf:.4f}")


PMF at k=0: 0.0067
PMF at k=1: 0.0337
PMF at k=2: 0.0842
PMF at k=3: 0.1404
PMF at k=4: 0.1755
PMF at k=5: 0.1755
PMF at k=6: 0.1462
PMF at k=7: 0.1044
PMF at k=8: 0.0653
PMF at k=9: 0.0363
PMF at k=10: 0.0181


In [ ]:
11) A company wants to test iN a new website layout leads to a higher conversion rate (percentage oN visitors
who make a purchase). They collect data Nrom the old and new layouts to compare.


To ge<erate the data use the followi<g comma<d:

```python

import <umpy as <p

# 50 purchases out of 1000 visitors

old_layout = <p.array([1] * 50 + [0] * 950)

# 70 purchases out of 1000 visitors  

<ew_layout = <p.array([1] * 70 + [0] * 930)

  ```

Apply z-test to find which layout is successful.

In [ ]:
To determine if the new website layout leads to a significantly higher conversion rate compared to the old layout, you can use a z-test for proportions. Here's a step-by-step guide to performing the z-test:

Steps to Perform the Z-Test:
Calculate the Proportions:

Compute the conversion rate (proportion of purchases) for both the old and new layouts.
Calculate the Combined Proportion:

This is the proportion of purchases across both groups combined.
Calculate the Standard Error:

The standard error of the difference between the two proportions.
Compute the Z-Score:

This measures how many standard errors the observed difference between the proportions is away from zero (the null hypothesis of no difference).
Calculate the P-Value:

Determine the probability of observing a z-score as extreme as, or more extreme than, the calculated z-score under the null hypothesis.

In [1]:
import numpy as np
from scipy import stats

# Generate data
old_layout = np.array([1] * 50 + [0] * 950)
new_layout = np.array([1] * 70 + [0] * 930)

# Calculate the proportions
p_old = np.mean(old_layout)
p_new = np.mean(new_layout)

# Calculate the combined proportion
p_combined = (np.sum(old_layout) + np.sum(new_layout)) / (len(old_layout) + len(new_layout))

# Calculate the standard error
se = np.sqrt(p_combined * (1 - p_combined) * (1 / len(old_layout) + 1 / len(new_layout)))

# Calculate the z-score
z_score = (p_new - p_old) / se

# Calculate the p-value (one-sided test)
p_value = 1 - stats.norm.cdf(z_score)

print(f"Old Layout Conversion Rate: {p_old:.4f}")
print(f"New Layout Conversion Rate: {p_new:.4f}")
print(f"Z-Score: {z_score:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The new layout is significantly better than the old layout.")
else:
    print("There is no significant difference between the new layout and the old layout.")


Old Layout Conversion Rate: 0.0500
New Layout Conversion Rate: 0.0700
Z-Score: 1.8831
P-Value: 0.0298
The new layout is significantly better than the old layout.


In [ ]:
Proportions:

p_old: Proportion of purchases in the old layout.
p_new: Proportion of purchases in the new layout.
Combined Proportion:

p_combined: Overall proportion of purchases combining both layouts.
Standard Error:

se: Standard error of the difference between the two proportions.
Z-Score:

Measures the difference between p_new and p_old in units of the standard error.
P-Value:

Probability of observing a z-score as extreme or more extreme than the calculated z-score under the null hypothesis.

In [ ]:
12) A tutoring service claims that its program improves students' exam scores. A sample oN students who
participated in the program was taken, and their scores beNore and aNter the program were recorded.


Use the below code to ge<erate samples of respective arrays of marks:

```python

before_program = <p.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])

after_program = <p.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

```

Use z-test to fi<d if the claims made by tutor are true or false.

In [ ]:
To test whether the tutoring program has a significant effect on students' exam scores, you can use a paired z-test (or a t-test, which is more common for small sample sizes) for the differences between the scores before and after the program. Here’s how to perform the z-test for paired samples:

Steps to Perform the Paired Z-Test:
Calculate the Differences:

Compute the difference between scores before and after the program for each student.
Calculate the Mean and Standard Deviation of the Differences:

Mean difference and standard deviation of the differences are needed to compute the z-score.
Calculate the Standard Error:

This is the standard deviation of the differences divided by the square root of the sample size.
Compute the Z-Score:

This measures how many standard errors the mean difference is away from zero (the null hypothesis of no effect).
Calculate the P-Value:

Determine the probability of observing a z-score as extreme as, or more extreme than, the calculated z-score under the null hypothesis.
Here’s the Python code to perform the paired z-test:

In [2]:
import numpy as np
from scipy import stats

# Sample data
before_program = np.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])
after_program = np.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

# Calculate the differences
differences = after_program - before_program

# Calculate the mean and standard deviation of the differences
mean_diff = np.mean(differences)
std_dev_diff = np.std(differences, ddof=0)  # Population standard deviation for z-test

# Calculate the standard error
n = len(differences)
se = std_dev_diff / np.sqrt(n)

# Calculate the z-score
z_score = mean_diff / se

# Calculate the p-value (two-sided test)
p_value = 2 * (1 - stats.norm.cdf(np.abs(z_score)))

print(f"Mean Difference: {mean_diff:.2f}")
print(f"Standard Deviation of Differences: {std_dev_diff:.2f}")
print(f"Standard Error: {se:.2f}")
print(f"Z-Score: {z_score:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The tutoring program has a significant effect on students' scores.")
else:
    print("There is no significant effect of the tutoring program on students' scores.")


Mean Difference: 3.80
Standard Deviation of Differences: 2.48
Standard Error: 0.78
Z-Score: 4.84
P-Value: 0.0000
The tutoring program has a significant effect on students' scores.


In [ ]:
Differences:

differences: Array of score differences (after - before).
Mean and Standard Deviation:

mean_diff: Mean of the differences.
std_dev_diff: Standard deviation of the differences.
Standard Error:

se: Standard error of the mean difference.
Z-Score:

Measures how far the mean difference is from zero in standard error units.
P-Value:

The probability of observing a z-score as extreme or more extreme under the null hypothesis. A two-sided test is used here to check if the mean difference is significantly different from zero in either direction.
Note: For smaller sample sizes, the paired t-test might be more appropriate than the z-test. If you want to use the t-test instead, you can replace the z-test calculations with a t-test using scipy.stats.ttest_rel.

In [ ]:
13) A pharmaceutical company wants to determine iN a new drug is eNNective in reducing blood pressure. They
conduct a study and record blood pressure measurements beNore and aNter administering the drug.


Use the below code to ge<erate samples of respective arrays of blood pressure:


```python

before_drug = <p.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])

after_drug = <p.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

  ```


Impleme<t z-test to fi<d if the drug really works or <ot

In [ ]:
To determine if the new drug is effective in reducing blood pressure, we can perform a paired z-test on the differences between blood pressure measurements before and after administering the drug. This will help us determine if there is a statistically significant reduction in blood pressure.

Here’s the step-by-step process and Python code to perform the z-test:

Steps to Perform the Paired Z-Test:
Calculate the Differences:

Compute the difference between the blood pressure measurements before and after the drug for each participant.
Calculate the Mean and Standard Deviation of the Differences:

Mean difference and standard deviation of the differences are needed to compute the z-score.
Calculate the Standard Error:

This is the standard deviation of the differences divided by the square root of the sample size.
Compute the Z-Score:

This measures how many standard errors the mean difference is away from zero (the null hypothesis of no effect).
Calculate the P-Value:

Determine the probability of observing a z-score as extreme as, or more extreme than, the calculated z-score under the null hypothesis.
Here’s the Python code to perform the paired z-test:


In [3]:
import numpy as np
from scipy import stats

# Sample data
before_drug = np.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])
after_drug = np.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

# Calculate the differences
differences = before_drug - after_drug

# Calculate the mean and standard deviation of the differences
mean_diff = np.mean(differences)
std_dev_diff = np.std(differences, ddof=0)  # Population standard deviation for z-test

# Calculate the standard error
n = len(differences)
se = std_dev_diff / np.sqrt(n)

# Calculate the z-score
z_score = mean_diff / se

# Calculate the p-value (two-sided test)
p_value = 2 * (1 - stats.norm.cdf(np.abs(z_score)))

print(f"Mean Difference: {mean_diff:.2f}")
print(f"Standard Deviation of Differences: {std_dev_diff:.2f}")
print(f"Standard Error: {se:.2f}")
print(f"Z-Score: {z_score:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The drug has a significant effect on reducing blood pressure.")
else:
    print("There is no significant effect of the drug on blood pressure.")


Mean Difference: 10.10
Standard Deviation of Differences: 3.01
Standard Error: 0.95
Z-Score: 10.59
P-Value: 0.0000
The drug has a significant effect on reducing blood pressure.


In [ ]:
Explanation:
Differences:

differences: Array of differences (before - after).
Mean and Standard Deviation:

mean_diff: Mean of the differences.
std_dev_diff: Standard deviation of the differences.
Standard Error:

se: Standard error of the mean difference.
Z-Score:

Measures how far the mean difference is from zero in standard error units.
P-Value:

The probability of observing a z-score as extreme or more extreme under the null hypothesis. A two-sided test is used to check if there is a significant reduction in blood pressure.
Note: While the z-test is appropriate for large sample sizes, for small sample sizes, a paired t-test might be more appropriate. If you wish to perform a paired t-test, you can use scipy.stats.ttest_rel instead.

In [ ]:
14) A custo:er service depart:ent clai:s that their average response ti:e is less than 5 :inutesV A sa:ple
of recent custo:er interactions was taken, and the response ti:es were recorded.


Impleme3t the below code to ge3erate the array of respo3se time:

```python

respo3se_times = 3p.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

```

Impleme3t z-test to fi3d the claims made by customer service departme3t are tru or false.

In [ ]:
To determine if the average response time is less than 5 minutes based on the customer service department's claim, we can perform a one-sample z-test. This test will check if the sample mean response time is significantly less than the claimed average of 5 minutes.

Steps to Perform the One-Sample Z-Test:
Calculate the Sample Mean:

Compute the average of the response times in the sample.
Calculate the Sample Standard Deviation:

Compute the standard deviation of the response times.
Calculate the Standard Error:

This is the standard deviation divided by the square root of the sample size.
Compute the Z-Score:

This measures how many standard errors the sample mean is away from the claimed mean of 5 minutes.
Calculate the P-Value:


In [4]:

import numpy as np
from scipy import stats

# Sample data
response_times = np.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

# Claimed mean response time
claimed_mean = 5.0

# Calculate the sample mean and standard deviation
sample_mean = np.mean(response_times)
sample_std_dev = np.std(response_times, ddof=0)  # Population standard deviation for z-test

# Calculate the standard error
n = len(response_times)
se = sample_std_dev / np.sqrt(n)

# Calculate the z-score
z_score = (sample_mean - claimed_mean) / se

# Calculate the p-value (one-sided test, since we are testing if the mean is less than 5)
p_value = stats.norm.cdf(z_score)

print(f"Sample Mean: {sample_mean:.2f}")
print(f"Sample Standard Deviation: {sample_std_dev:.2f}")
print(f"Standard Error: {se:.2f}")
print(f"Z-Score: {z_score:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The average response time is significantly less than 5 minutes.")
else:
    print("There is no significant evidence that the average response time is less than 5 minutes.")


Sample Mean: 4.57
Sample Standard Deviation: 0.41
Standard Error: 0.13
Z-Score: -3.36
P-Value: 0.0004
The average response time is significantly less than 5 minutes.


In [ ]:
Explanation:
Sample Mean:

sample_mean: Average of the response times.
Sample Standard Deviation:

sample_std_dev: Standard deviation of the response times.
Standard Error:

se: Standard error of the mean response time.
Z-Score:

Measures how far the sample mean is from the claimed mean of 5 minutes in standard error units.
P-Value:

The probability of observing a z-score as extreme as, or more extreme than, the calculated z-score under the null hypothesis. A one-sided test is used because the claim is that the mean is less than 5 minutes.
If the p-value is less than 0.05, it indicates that there is significant evidence to support the claim that the average response time is less than 5 minutes.

In [ ]:
15)A co:pany is testing two different website layouts to see which one leads to higher click-through ratesV
Write a Python function to perfor: an A/B test analysis, including calculating the t-statistic, degrees of
freedo:, and p-value.


Use the followi3g data:

```python

layout_a_clicks = [28, 32, 33, 29, 31, 34, 30, 35, 36, 37]

layout_b_clicks = [40, 41, 38, 42, 39, 44, 43, 41, 45, 47]

In [ ]:

import numpy as np
from scipy import stats

def ab_test_analysis(layout_a_clicks, layout_b_clicks):
    # Convert lists to numpy arrays
    layout_a_clicks = np.array(layout_a_clicks)
    layout_b_clicks = np.array(layout_b_clicks)
    
    # Calculate sample means
    mean_a = np.mean(layout_a_clicks)
    mean_b = np.mean(layout_b_clicks)
    
    # Calculate sample standard deviations
    std_dev_a = np.std(layout_a_clicks, ddof=1)
    std_dev_b = np.std(layout_b_clicks, ddof=1)
    
    # Calculate sample sizes
    n_a = len(layout_a_clicks)
    n_b = len(layout_b_clicks)
    
    # Calculate the standard error of the difference in means
    se = np.sqrt((std_dev_a**2 / n_a) + (std_dev_b**2 / n_b))
    
    # Calculate the t-statistic
    t_statistic = (mean_a - mean_b) / se
    
    # Calculate degrees of freedom
    df = ((std_dev_a**2 / n_a + std_dev_b**2 / n_b) ** 2) / \
         (((std_dev_a**2 / n_a) ** 2 / (n_a - 1)) + ((std_dev_b**2 / n_b) ** 2 / (n_b - 1)))
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    return t_statistic, df, p_value

# Sample data
layout_a_clicks = [28, 32, 33, 29, 31, 34, 30, 35, 36, 37]
layout_b_clicks = [40, 41, 38, 42, 39, 44, 43, 41, 45, 47]

# Perform A/B test analysis
t_statistic, df, p_value = ab_test_analysis(layout_a_clicks, layout_b_clicks)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"Degrees of Freedom: {df:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in click-through rates between the two layouts.")
else:
    print("There is no significant difference in click-through rates between the two layouts.")


In [ ]:
Explanation:
Sample Means:

mean_a: Average number of clicks for layout A.
mean_b: Average number of clicks for layout B.
Sample Standard Deviations:

std_dev_a: Standard deviation of clicks for layout A.
std_dev_b: Standard deviation of clicks for layout B.
Standard Error:

se: Standard error of the difference between the two sample means.
T-Statistic:

Measures how far apart the sample means are in units of the standard error.
Degrees of Freedom:

Calculated using the formula for Welch's approximation, which accounts for different variances and sample sizes.
P-Value:

The probability of observing a t-statistic as extreme or more extreme under the null hypothesis.
If the p-value is less than 0.05, it indicates a significant difference between the click-through rates of the two layouts.

In [ ]:
 16)A phar:aceutical co:pany wants to deter:ine if a new drug is :ore effective than an existing drug in
reducing cholesterol levelsV Create a progra: to analyze the clinical trial data and calculate the tstatistic and p-value for the treat:ent effect.


Use the followi3g data of cholestrol level:

```python

existi3g_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]

3ew_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

In [5]:
import numpy as np
from scipy import stats

def t_test_for_treatment_effect(existing_drug_levels, new_drug_levels):
    # Convert lists to numpy arrays
    existing_drug_levels = np.array(existing_drug_levels)
    new_drug_levels = np.array(new_drug_levels)
    
    # Calculate sample means
    mean_existing = np.mean(existing_drug_levels)
    mean_new = np.mean(new_drug_levels)
    
    # Calculate sample standard deviations
    std_dev_existing = np.std(existing_drug_levels, ddof=1)  # Sample standard deviation
    std_dev_new = np.std(new_drug_levels, ddof=1)  # Sample standard deviation
    
    # Calculate sample sizes
    n_existing = len(existing_drug_levels)
    n_new = len(new_drug_levels)
    
    # Calculate the standard error of the difference in means
    se = np.sqrt((std_dev_existing**2 / n_existing) + (std_dev_new**2 / n_new))
    
    # Calculate the t-statistic
    t_statistic = (mean_existing - mean_new) / se
    
    # Calculate degrees of freedom using Welch's approximation
    df = ((std_dev_existing**2 / n_existing + std_dev_new**2 / n_new) ** 2) / \
         (((std_dev_existing**2 / n_existing) ** 2 / (n_existing - 1)) + ((std_dev_new**2 / n_new) ** 2 / (n_new - 1)))
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    return t_statistic, df, p_value

# Sample data
existing_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]
new_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

# Perform t-test for treatment effect
t_statistic, df, p_value = t_test_for_treatment_effect(existing_drug_levels, new_drug_levels)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"Degrees of Freedom: {df:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The new drug is significantly more effective than the existing drug in reducing cholesterol levels.")
else:
    print("There is no significant difference between the new drug and the existing drug in reducing cholesterol levels.")


T-Statistic: 4.1405
Degrees of Freedom: 17.87
P-Value: 0.0006
The new drug is significantly more effective than the existing drug in reducing cholesterol levels.


In [ ]:
17) A school district introduces an educational intervention program to improve math scores Write a Python
function to analyze pre- and post-intervention test scores, calculating the t-statistic and p-value to
deter:ine if the intervention had a significant i:pact.


Use the followi3g data of test score:


  ```python

  pre_i3terve3tio3_scores = [80, 85, 90, 75, 88, 82, 92, 78, 85, 87]

  post_i3terve3tio3_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]

In [6]:
import numpy as np
from scipy import stats

def paired_t_test(pre_intervention_scores, post_intervention_scores):
    # Convert lists to numpy arrays
    pre_intervention_scores = np.array(pre_intervention_scores)
    post_intervention_scores = np.array(post_intervention_scores)
    
    # Calculate the differences
    differences = post_intervention_scores - pre_intervention_scores
    
    # Calculate the mean and standard deviation of the differences
    mean_diff = np.mean(differences)
    std_dev_diff = np.std(differences, ddof=1)  # Sample standard deviation
    
    # Calculate the standard error of the mean difference
    n = len(differences)
    se = std_dev_diff / np.sqrt(n)
    
    # Calculate the t-statistic
    t_statistic = mean_diff / se
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=n-1))
    
    return t_statistic, p_value

# Sample data
pre_intervention_scores = [80, 85, 90, 75, 88, 82, 92, 78, 85, 87]
post_intervention_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]

# Perform paired t-test
t_statistic, p_value = paired_t_test(pre_intervention_scores, post_intervention_scores)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("The educational intervention had a significant impact on math scores.")
else:
    print("There is no significant impact of the educational intervention on math scores.")


T-Statistic: 4.4284
P-Value: 0.0017
The educational intervention had a significant impact on math scores.


In [ ]:
18) An HR department wants to investigate i@ there's a gender-based salary gap within the company. Develop
a program to analyze salary data, calculate the t-statistic, and determine i@ there's a statistically
signi@icant di@@erence between the average salaries o@ male and @emale employees.


Use the below code to generate synthetic dataY
```python

# Generate synthetic salary data for male and female employees

np.random.seed(0)  # For reproducibility

male_salaries = np.random.normal(loc=50000, scale=10000, size=20)

female_salaries = np.random.normal(loc=55000, scale=9000, size=20)

In [7]:
import numpy as np
from scipy import stats

def t_test_gender_salary(male_salaries, female_salaries):
    # Calculate sample means
    mean_male = np.mean(male_salaries)
    mean_female = np.mean(female_salaries)
    
    # Calculate sample standard deviations
    std_dev_male = np.std(male_salaries, ddof=1)  # Sample standard deviation
    std_dev_female = np.std(female_salaries, ddof=1)  # Sample standard deviation
    
    # Calculate sample sizes
    n_male = len(male_salaries)
    n_female = len(female_salaries)
    
    # Calculate the standard error of the difference in means
    se = np.sqrt((std_dev_male**2 / n_male) + (std_dev_female**2 / n_female))
    
    # Calculate the t-statistic
    t_statistic = (mean_male - mean_female) / se
    
    # Calculate degrees of freedom using Welch's approximation
    df = ((std_dev_male**2 / n_male + std_dev_female**2 / n_female) ** 2) / \
         (((std_dev_male**2 / n_male) ** 2 / (n_male - 1)) + ((std_dev_female**2 / n_female) ** 2 / (n_female - 1)))
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    return t_statistic, df, p_value

# Generate synthetic salary data
np.random.seed(0)  # For reproducibility
male_salaries = np.random.normal(loc=50000, scale=10000, size=20)
female_salaries = np.random.normal(loc=55000, scale=9000, size=20)

# Perform t-test for salary difference by gender
t_statistic, df, p_value = t_test_gender_salary(male_salaries, female_salaries)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"Degrees of Freedom: {df:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in average salaries between male and female employees.")
else:
    print("There is no significant difference in average salaries between male and female employees.")


T-Statistic: 0.0611
Degrees of Freedom: 36.17
P-Value: 0.9516
There is no significant difference in average salaries between male and female employees.


In [ ]:
19) A manu@acturer produces two di@@erent versions o@ a product and wants to compare their quality scores.
Create a Python @unction to analyze quality assessment data, calculate the t-statistic, and decide
whether there's a signi@icant di@@erence in quality between the two versions.


Use the following dataY
```python

version1_scores = [85, 88, 82, 89, 87, 84, 90, 88, 85, 86, 91, 83, 87, 84, 89, 86, 84, 88, 85, 86, 89, 90, 87, 88, 85]

version2_scores = [80, 78, 83, 81, 79, 82, 76, 80, 78, 81, 77, 82, 80, 79, 82, 79, 80, 81, 79, 82, 79, 78, 80, 81, 82]

In [8]:
import numpy as np
from scipy import stats

def t_test_quality(version1_scores, version2_scores):
    # Convert lists to numpy arrays
    version1_scores = np.array(version1_scores)
    version2_scores = np.array(version2_scores)
    
    # Calculate sample means
    mean_version1 = np.mean(version1_scores)
    mean_version2 = np.mean(version2_scores)
    
    # Calculate sample standard deviations
    std_dev_version1 = np.std(version1_scores, ddof=1)  # Sample standard deviation
    std_dev_version2 = np.std(version2_scores, ddof=1)  # Sample standard deviation
    
    # Calculate sample sizes
    n_version1 = len(version1_scores)
    n_version2 = len(version2_scores)
    
    # Calculate the standard error of the difference in means
    se = np.sqrt((std_dev_version1**2 / n_version1) + (std_dev_version2**2 / n_version2))
    
    # Calculate the t-statistic
    t_statistic = (mean_version1 - mean_version2) / se
    
    # Calculate degrees of freedom using Welch's approximation
    df = ((std_dev_version1**2 / n_version1 + std_dev_version2**2 / n_version2) ** 2) / \
         (((std_dev_version1**2 / n_version1) ** 2 / (n_version1 - 1)) + ((std_dev_version2**2 / n_version2) ** 2 / (n_version2 - 1)))
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    return t_statistic, df, p_value

# Sample data
version1_scores = [85, 88, 82, 89, 87, 84, 90, 88, 85, 86, 91, 83, 87, 84, 89, 86, 84, 88, 85, 86, 89, 90, 87, 88, 85]
version2_scores = [80, 78, 83, 81, 79, 82, 76, 80, 78, 81, 77, 82, 80, 79, 82, 79, 80, 81, 79, 82, 79, 78, 80, 81, 82]

# Perform t-test for quality scores difference
t_statistic, df, p_value = t_test_quality(version1_scores, version2_scores)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"Degrees of Freedom: {df:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in quality between the two versions.")
else:
    print("There is no significant difference in quality between the two versions.")


T-Statistic: 11.3258
Degrees of Freedom: 44.47
P-Value: 0.0000
There is a significant difference in quality between the two versions.


In [ ]:
 20. A restaurant chain collects customer satis@action scores @or two di@@erent branches. Write a program to
analyze the scores, calculate the t-statistic, and determine i@ there's a statistically signi@icant di@@erence in
customer satis@action between the branches.


Use the below data of scores:

  ```python

branch_a_scores = [4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 4, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 3, 5, 4, 4, 5, 3, 4, 5, 4]

branch_b_scores = [3, 4, 2, 3, 4, 3, 4, 2, 3, 3, 4, 3, 3, 2, 3, 4, 4, 3, 2, 3, 4, 3, 2, 4, 3, 3, 4, 2, 3, 4, 3]

In [9]:
import numpy as np
from scipy import stats

def t_test_satisfaction(branch_a_scores, branch_b_scores):
    # Convert lists to numpy arrays
    branch_a_scores = np.array(branch_a_scores)
    branch_b_scores = np.array(branch_b_scores)
    
    # Calculate sample means
    mean_branch_a = np.mean(branch_a_scores)
    mean_branch_b = np.mean(branch_b_scores)
    
    # Calculate sample standard deviations
    std_dev_branch_a = np.std(branch_a_scores, ddof=1)  # Sample standard deviation
    std_dev_branch_b = np.std(branch_b_scores, ddof=1)  # Sample standard deviation
    
    # Calculate sample sizes
    n_branch_a = len(branch_a_scores)
    n_branch_b = len(branch_b_scores)
    
    # Calculate the standard error of the difference in means
    se = np.sqrt((std_dev_branch_a**2 / n_branch_a) + (std_dev_branch_b**2 / n_branch_b))
    
    # Calculate the t-statistic
    t_statistic = (mean_branch_a - mean_branch_b) / se
    
    # Calculate degrees of freedom using Welch's approximation
    df = ((std_dev_branch_a**2 / n_branch_a + std_dev_branch_b**2 / n_branch_b) ** 2) / \
         (((std_dev_branch_a**2 / n_branch_a) ** 2 / (n_branch_a - 1)) + ((std_dev_branch_b**2 / n_branch_b) ** 2 / (n_branch_b - 1)))
    
    # Calculate the p-value (two-sided test)
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    return t_statistic, df, p_value

# Sample data
branch_a_scores = [4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 4, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 3, 5, 4, 4, 5, 3, 4, 5, 4]
branch_b_scores = [3, 4, 2, 3, 4, 3, 4, 2, 3, 3, 4, 3, 3, 2, 3, 4, 4, 3, 2, 3, 4, 3, 2, 4, 3, 3, 4, 2, 3, 4, 3]

# Perform t-test for satisfaction scores difference
t_statistic, df, p_value = t_test_satisfaction(branch_a_scores, branch_b_scores)

print(f"T-Statistic: {t_statistic:.4f}")
print(f"Degrees of Freedom: {df:.2f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in customer satisfaction between the two branches.")
else:
    print("There is no significant difference in customer satisfaction between the two branches.")


T-Statistic: 5.4801
Degrees of Freedom: 60.00
P-Value: 0.0000
There is a significant difference in customer satisfaction between the two branches.


In [ ]:
21) A political analyst wants to determine i@ there is a signi@icant association between age groups and voter
pre@erences FCandidate A or Candidate B). They collect data @rom a sample o@ 500 voters and classi@y
them into di@@erent age groups and candidate pre@erences. Per@orm a Chi-Square test to determine i@
there is a signi@icant association between age groups and voter pre@erences.


Use the below code to generate data:

```python

np.random.seed(0)

age_groups = np.random.choice([ 18 30 , 31 50 , 51+', 51+'], size=30)

voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=30)

In [10]:
import numpy as np
from scipy import stats

def chi_square_test(age_groups, voter_preferences):
    # Create a contingency table
    contingency_table = np.zeros((3, 2), dtype=int)  # 3 age groups x 2 candidate preferences

    # Map age groups and preferences to indices
    age_map = {'18-30': 0, '31-50': 1, '51+': 2}
    preference_map = {'Candidate A': 0, 'Candidate B': 1}

    for age, preference in zip(age_groups, voter_preferences):
        age_index = age_map[age]
        preference_index = preference_map[preference]
        contingency_table[age_index, preference_index] += 1

    # Perform the Chi-Square test
    chi2_stat, p_value, _, _ = stats.chi2_contingency(contingency_table)
    
    return chi2_stat, p_value, contingency_table

# Generate synthetic data
np.random.seed(0)
age_groups = np.random.choice(['18-30', '31-50', '51+'], size=500)
voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=500)

# Perform Chi-Square test
chi2_stat, p_value, contingency_table = chi_square_test(age_groups, voter_preferences)

print("Contingency Table:")
print(contingency_table)
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant association between age groups and voter preferences.")
else:
    print("There is no significant association between age groups and voter preferences.")


Contingency Table:
[[95 87]
 [87 82]
 [84 65]]
Chi-Square Statistic: 0.8780
P-Value: 0.6447
There is no significant association between age groups and voter preferences.


In [ ]:
 22. A company conducted a customer satisfaction survey to determine if there is a significant relationship
between product satisfaction levels (Satisfied, Neutral, Dissatisfied) and the region where customers are
located (East, West, North, South). The survey data is summarized in a contingency table. Conduct a ChiSquare test to determine if there is a significant relationship between product satisfaction levels and
customer regions.


Sample data:

```python

#Sample data: Product satisfaction levels (rows) vs. Customer regions (columns)

data = np.array([[50, 30, 40, 20], [30, 40, 30, 50], [20, 30, 40, 30]])



In [11]:
import numpy as np
from scipy import stats

def chi_square_test(data):
    # Perform the Chi-Square test
    chi2_stat, p_value, dof, expected = stats.chi2_contingency(data)
    
    return chi2_stat, p_value, dof, expected

# Sample data: Product satisfaction levels (rows) vs. Customer regions (columns)
data = np.array([[50, 30, 40, 20], [30, 40, 30, 50], [20, 30, 40, 30]])

# Perform Chi-Square test
chi2_stat, p_value, dof, expected = chi_square_test(data)

print("Contingency Table:")
print(data)
print("\nExpected Frequencies:")
print(expected)
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"P-Value: {p_value:.4f}")
print(f"Degrees of Freedom: {dof}")

# Interpretation
if p_value < 0.05:
    print("There is a significant relationship between product satisfaction levels and customer regions.")
else:
    print("There is no significant relationship between product satisfaction levels and customer regions.")


Contingency Table:
[[50 30 40 20]
 [30 40 30 50]
 [20 30 40 30]]

Expected Frequencies:
[[34.14634146 34.14634146 37.56097561 34.14634146]
 [36.58536585 36.58536585 40.24390244 36.58536585]
 [29.26829268 29.26829268 32.19512195 29.26829268]]
Chi-Square Statistic: 27.7771
P-Value: 0.0001
Degrees of Freedom: 6
There is a significant relationship between product satisfaction levels and customer regions.


In [ ]:
 23. A company implemented an employee training program to improve job performance (Effective, Neutral,
Ineffective). After the training, they collected data from a sample of employees and classified them based
on their job performance before and after the training. Perform a Chi-Square test to determine if there is a
significant difference between job performance levels before and after the training.


Sample data:

```python

# Sample data: Job performance levels before (rows) and after (columns) training

data = np.array([[50, 30, 20], [30, 40, 30], [20, 30, 40]])

In [12]:
import numpy as np
from scipy import stats

def chi_square_test(data):
    # Perform the Chi-Square test
    chi2_stat, p_value, dof, expected = stats.chi2_contingency(data)
    
    return chi2_stat, p_value, dof, expected

# Sample data: Job performance levels before (rows) and after (columns) training
data = np.array([[50, 30, 20], [30, 40, 30], [20, 30, 40]])

# Perform Chi-Square test
chi2_stat, p_value, dof, expected = chi_square_test(data)

print("Contingency Table:")
print(data)
print("\nExpected Frequencies:")
print(expected)
print(f"Chi-Square Statistic: {chi2_stat:.4f}")
print(f"P-Value: {p_value:.4f}")
print(f"Degrees of Freedom: {dof}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in job performance levels before and after the training.")
else:
    print("There is no significant difference in job performance levels before and after the training.")


Contingency Table:
[[50 30 20]
 [30 40 30]
 [20 30 40]]

Expected Frequencies:
[[34.48275862 34.48275862 31.03448276]
 [34.48275862 34.48275862 31.03448276]
 [31.03448276 31.03448276 27.93103448]]
Chi-Square Statistic: 22.1617
P-Value: 0.0002
Degrees of Freedom: 4
There is a significant difference in job performance levels before and after the training.


In [ ]:
 24. A company produces three different versions of a product: Standard, Premium, and Deluxe. The
company wants to determine if there is a significant difference in customer satisfaction scores among the
three product versions. They conducted a survey and collected customer satisfaction scores for each
version from a random sample of customers. Perform an ANOVA test to determine if there is a significant
difference in customer satisfaction scores.


  Use the following data:

  ```python

  # Sample data: Customer satisfaction scores for each product version

  standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]

  premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]

  deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

In [13]:
import numpy as np
from scipy import stats

def anova_test(standard_scores, premium_scores, deluxe_scores):
    # Perform one-way ANOVA
    f_statistic, p_value = stats.f_oneway(standard_scores, premium_scores, deluxe_scores)
    
    return f_statistic, p_value

# Sample data: Customer satisfaction scores for each product version
standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]
premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]
deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

# Perform ANOVA test
f_statistic, p_value = anova_test(standard_scores, premium_scores, deluxe_scores)

print(f"F-Statistic: {f_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
if p_value < 0.05:
    print("There is a significant difference in customer satisfaction scores among the three product versions.")
else:
    print("There is no significant difference in customer satisfaction scores among the three product versions.")


F-Statistic: 27.0356
P-Value: 0.0000
There is a significant difference in customer satisfaction scores among the three product versions.
